export const classesList = [
  {
    subject: "",
    classTitle: "optics",
    photoUrl: "../assets/img/optics.png",
    index: 4,
    precent: 100,
    num: 12,
    id: 1,
    introPhoto: "intro-optics",
  },
  {
    subject: "",
    classTitle: "electricity",
    photoUrl: "../assets/img/electricity.png",
    index: 3,
    precent: 100,
    num: 43,
    id: 2,
    introPhoto: "intro-electricity",
  },
  {
    subject: "",
    classTitle: "motion",
    photoUrl: "../assets/img/optics.png",
    index: 2,
    precent: 100,
    num: 50,
    id: 3,
    introPhoto: "intro-motion",
  },
  {
    subject: "",
    classTitle: "fluids",
    photoUrl: "../assets/img/optics.png",
    index: 1,
    precent: 100,
    num: 32,
    id: 4,
    introPhoto: "intro-fluid",
  },
];

export const qestionList = [
  {
    qestionId: 1,
    qestion: "what are water made of ?",
    answers: ["air", "H2O muleculs", "hidrogen", "oxigen"],
    rightAnswer: "H2O muleculs",
    subject: "chemistry",
  },
  {
    qestionId: 2,
    qestion: "",
    answers: [],
    rightAnswer: "",
    subject: "",
  },
  {
    qestionId: 3,
    qestion: "",
    answers: [],
    rightAnswer: "",
    subject: "",
  },
  {
    qestionId: 4,
    qestion: "",
    answers: [],
    rightAnswer: "",
    subject: "",
  },
];
