export const classesList = [
  {
    subject: "",
    classTitle: "optics",
    photoUrl: "../assets/img/optics.png",
    index: 4,
    precent: 100,
    num: 12,
    id: 1,
    introPhoto: "intro-optics",
  },
  {
    subject: "",
    classTitle: "electricity",
    photoUrl: "../assets/img/electricity.png",
    index: 3,
    precent: 100,
    num: 43,
    id: 2,
    introPhoto: "intro-electricity",
  },
  {
    subject: "",
    classTitle: "motion",
    photoUrl: "../assets/img/optics.png",
    index: 2,
    precent: 100,
    num: 50,
    id: 3,
    introPhoto: "intro-motion",
  },
  {
    subject: "",
    classTitle: "fluids",
    photoUrl: "../assets/img/optics.png",
    index: 1,
    precent: 100,
    num: 32,
    id: 4,
    introPhoto: "intro-fluid",
  },
];
